// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqiyritnhssnzjrlsnyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxaXlyaXRuaHNzbnpqcmxzbnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDg1MjcsImV4cCI6MjA3MjE4NDUyN30.umzgVP3qwB04YWl1ukP3lGF0txEuIdGkbrszp58QJ9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});